spring.application.name=crucial

# Spring DataSource
spring.data.source.url = jpc:mysql://localhost:3306/journal
spring.datasource.connectionProperties=useUnicode=true;characterEnding=Utf-8
spring.datasouce.username = springboot
spring.datasource.password = springboot
spring.datasource.testWhileIdle = true
spring.datasouce.validationQuery = SELECT 1

# JPA-Hibernate
spring.jpa.show-sql = true
spring.jpa.hibernate.ddl-auto = create-drop
spring.jpa.hibernate.naming.implicit-strategy = org.hibbernate.cfg.ImprovedNamingStrategy
spring.jpa.properties.hibernate.dialect = org.hibernate.dialect.MySQL5Dialect

spring.data.rest.basepath=/api

# Security
spring.security.user.name= springBoot
security.user.password = isawesome

